export const FormSignUp = {
 SIGN_UP_START: "SIGN_UP_START",
 SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
 SIGN_UP_FAIL: "SIGN_UP_FAIL"
};

export const FormSignIn = {
 SIGN_IN_START: "SIGN_IN_START",
 SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
 SIGN_IN_FAIL: "SIGN_IN_FAIL"
}